environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Previous Visual Studio 2019
      PYTHON: "C:\\Python37"
    - APPVEYOR_BUILD_WORKER_IMAGE: Previous Ubuntu1804
      PYTHON: "3.7"
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS-Mojave
      PYTHON: "3.7"

install:
  - python -V
  - pip -V
  - pip install -r dev_requirements.txt
  - pip install -e .

test_script:
  - pytest --disable-pytest-warnings --cov-report=xml --cov=chepy --cov-config=.coveragerc tests/
  - coverage report -m
  - bandit --recursive chepy/ --ignore-nosec --skip B101,B413,B303,B310,B112,B304,B320,B410,B404
  - make -C docs/ clean html
  - pyinstaller cli.py --name chepy --onefile

artifacts:
  - dist/chepy