queries:
  - exclude: py/call-to-non-callable
  - exclude: py/redundant-else
  - exclude: py/catch-base-exception
  - exclude: py/similar-function

extraction:
  python:
    python_setup:
      version: 3
    index:
      include:
        - chepy