dist: bionic
language: python
python:
  - '3.7'
  - '3.6'
  - '3.5'
cache:
  - pip
before_install:
  - python -V
  - pip -V
  - pip install -e .
  - pip install pytest
  - pip install -e .
script:
  - pytest -v