dist: bionic
language: python
python:
- '3.6'
cache:
- pip
before_install:
- python -V
- pip -V
- pip install pytest pytest-cov bandit sphinx recommonmark
- pip install -e .
script:
- pytest --disable-pytest-warnings --cov-report=xml --cov=chepy --cov-config=.coveragerc
  tests/
- coverage report -m
- bandit --recursive chepy/ --ignore-nosec --skip B101,B413,B303,B310,B112,B304,B320,B410,B404
- make -C docs/ clean html
deploy:
  provider: pypi
  user: __token__
  password:
    secure: uhLPkQibP8u6mnTBq8tz8vx72FEse1rBCKiT0FAXWXOvmcdYEPRtFGQAjxFRemYHIpoYz3lK1MY9c0DRmz0vzkV+62FIQsLclzaHQH2XBf2mjpsNpGzvk4eXq5aNc003BH0n3UKuOJg9qJcBmqNh8k0QIY/lnFIGUDQzhtnplbCJHB7Cue8S8vuDgMZTj2I6l3obnYWv47jgcYqVBfJXYzIfJV+WX+n0coYbKlleiNlMZf7hwrMkNSnwoGUO04XHzIfPQ0TNSZNT7N/EShi77rYT+saY//X+0ydv/2NZ6izCg9gvZqNYRRBDmBBN0to/YTjDvtqt4eYKNPgscP65xD8dWZW2Kseg6CC6lJKwd0Mq65NPtLH+vwGt4Neg9eGxb6t2Wz2KN3DlUfhOnCDhumwD6nc8VwQuTzGZvsARPJ0uzHzi/b5dBD/+YguZjnLR2cmKBdq6YcQ1M8J1cmZvGl79I/IrjMkRBngcoCusJCKx2SyXtBMQYwFphEQb4dh8lL+NfmPGRP3rwMbZbzJTFQrJ9JcA1+tw7obVE6HKjuod9zbSBS2RfMOrHotckh8NNeP/6tdTf69wj+JcOkryl16uld+5pk3RObUcf+9jZ9RHE64xAE3+xBMnl0+/Plb3fBQ+tKuG2LsuV89hMF08R1yMYReiRGVyHMxrRrusdcU=
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true
